# Generated by Django 5.0 on 2024-06-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0027_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
