# Generated by Django 5.0 on 2024-10-08 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0029_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('time_stamp', models.DateField(verbose_name=datetime.date.today)),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
    ]
