# Generated by Django 5.0 on 2024-10-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0030_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='time_stamp',
        ),
    ]
