# Generated by Django 5.0 on 2024-10-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0031_remove_product_category_time_stamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Category',
        ),
    ]
