# Generated by Django 5.0 on 2024-10-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0032_delete_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
    ]
