# Generated by Django 5.0 on 2024-11-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0034_softdrink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
